import Head from "next/head";
import Home from "./home";
import Header from "../components/layout/Header";
import { Providers } from "../app/providers";

export default function Index() {

 

  return (
    <div className="dark">
      <Head>
        <title>Next.js | Food App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
        />
      </Head>
      <Providers>
        <Home />
      </Providers>
    </div>
  );
}

